#FROM paddlepaddle/paddle:2.4.1
#FROM  registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7

FROM python:3.7.16

RUN  sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt-get update && apt-get install libgl1-mesa-glx -y

RUN pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple

RUN pip install  "paddleocr>=2.0.1"  -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY . /root/PaddleOCR

EXPOSE 8080

CMD cd /root/PaddleOCR/web && \
    python3 index.py
