#FROM paddlepaddle/paddle:2.4.1
#FROM  registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7

FROM python:3.12

#RUN  sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt-get update && apt-get install libgl1-mesa-glx -y

RUN pip install paddlepaddle
#==2.6.1  

#-i https://mirror.baidu.com/pypi/simple

##用最新版本
RUN pip install pillow setuptools
RUN pip install  paddleocr  -i https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /PaddleOCR
COPY web  ./web

EXPOSE 8080

CMD cd web && \
    python3 index.py
#CMD ls   /PaddleOCR  
